/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_faculdade_Telas;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import projeto_faculdade.DAO.DaoTabela;
import projeto_faculdade.Fachada.Fachada;
import projeto_faculdade.Model.Aluno;
import projeto_faculdade.Model.Notas;

import projeto_faculdade.SqlUtil.SQL_Connection;

/**
 *
 * @author Sávio
 */
public class TelaNotas extends javax.swing.JFrame {

    int flag =0;
    Notas notas = new Notas();
    SQL_Connection conex_sql =  new SQL_Connection();
    public TelaNotas() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
        List alunos;
        
        Aluno aluno = new Aluno();
        alunos =Fachada.getInstance().getAllAluno();
       preencherTabela("select *from notas order by id");
       int index =0;
       while(alunos.size() > index ){
           ComboAluno.addItem(alunos.get(index));
           index++;
           
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonNovoAlunoNota = new javax.swing.JButton();
        ButtonEditar = new javax.swing.JButton();
        ButonSalvar = new javax.swing.JButton();
        ButonVoltar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        field_g5 = new javax.swing.JTextField();
        field_m5 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        field_h5 = new javax.swing.JTextField();
        field_p5 = new javax.swing.JTextField();
        field_a5 = new javax.swing.JTextField();
        field_c5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        field_g6 = new javax.swing.JTextField();
        field_m6 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        field_h6 = new javax.swing.JTextField();
        field_p6 = new javax.swing.JTextField();
        field_a6 = new javax.swing.JTextField();
        field_c6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        field_g7 = new javax.swing.JTextField();
        field_m7 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        field_h7 = new javax.swing.JTextField();
        field_p7 = new javax.swing.JTextField();
        field_a7 = new javax.swing.JTextField();
        field_c7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        field_g8 = new javax.swing.JTextField();
        field_m8 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        field_h8 = new javax.swing.JTextField();
        field_p8 = new javax.swing.JTextField();
        field_a8 = new javax.swing.JTextField();
        field_c8 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ComboAluno = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaNotas = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        fieldBuscarAluno = new javax.swing.JTextField();
        ButtonBuscar = new javax.swing.JButton();
        fieldID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        fieldNome = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonNovoAlunoNota.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        ButtonNovoAlunoNota.setForeground(new java.awt.Color(0, 0, 244));
        ButtonNovoAlunoNota.setText("Novo Aluno");
        ButtonNovoAlunoNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNovoAlunoNotaActionPerformed(evt);
            }
        });

        ButtonEditar.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        ButtonEditar.setForeground(new java.awt.Color(0, 0, 244));
        ButtonEditar.setText("Editar Notas");
        ButtonEditar.setEnabled(false);
        ButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarActionPerformed(evt);
            }
        });

        ButonSalvar.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        ButonSalvar.setForeground(new java.awt.Color(0, 0, 244));
        ButonSalvar.setText("Salvar Notas");
        ButonSalvar.setEnabled(false);
        ButonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButonSalvarActionPerformed(evt);
            }
        });

        ButonVoltar.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        ButonVoltar.setForeground(new java.awt.Color(0, 0, 244));
        ButonVoltar.setText("Voltar ao Menu");
        ButonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButonVoltarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        field_g5.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        field_g5.setForeground(new java.awt.Color(0, 0, 244));
        field_g5.setEnabled(false);

        field_m5.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        field_m5.setForeground(new java.awt.Color(0, 0, 244));
        field_m5.setEnabled(false);

        jTextField3.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 0, 244));
        jTextField3.setText("MÉDIA FINAL");

        field_h5.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        field_h5.setForeground(new java.awt.Color(0, 0, 244));
        field_h5.setEnabled(false);

        field_p5.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        field_p5.setForeground(new java.awt.Color(0, 0, 244));
        field_p5.setEnabled(false);
        field_p5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_p5ActionPerformed(evt);
            }
        });

        field_a5.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        field_a5.setForeground(new java.awt.Color(0, 0, 244));
        field_a5.setEnabled(false);

        field_c5.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        field_c5.setForeground(new java.awt.Color(0, 0, 244));
        field_c5.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(field_a5)
                            .addComponent(field_g5)
                            .addComponent(field_h5)
                            .addComponent(field_m5)
                            .addComponent(field_p5)
                            .addComponent(field_c5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(field_p5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(field_m5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(field_h5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(field_g5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(field_a5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(field_c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 244));
        jLabel7.setText("5ª Série");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 244));
        jLabel8.setText("6ª Série");

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        field_g6.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        field_g6.setForeground(new java.awt.Color(0, 0, 244));
        field_g6.setEnabled(false);

        field_m6.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        field_m6.setForeground(new java.awt.Color(0, 0, 244));
        field_m6.setEnabled(false);

        jTextField4.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(0, 0, 244));
        jTextField4.setText("MÉDIA FINAL");

        field_h6.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        field_h6.setForeground(new java.awt.Color(0, 0, 244));
        field_h6.setEnabled(false);

        field_p6.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        field_p6.setForeground(new java.awt.Color(0, 0, 244));
        field_p6.setEnabled(false);

        field_a6.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        field_a6.setForeground(new java.awt.Color(0, 0, 244));
        field_a6.setEnabled(false);

        field_c6.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        field_c6.setForeground(new java.awt.Color(0, 0, 244));
        field_c6.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(field_a6)
                            .addComponent(field_g6)
                            .addComponent(field_h6)
                            .addComponent(field_m6)
                            .addComponent(field_p6)
                            .addComponent(field_c6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(field_p6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(field_m6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(field_h6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(field_g6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(field_a6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(field_c6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 244));
        jLabel9.setText("7ª Série");

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        field_g7.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        field_g7.setForeground(new java.awt.Color(0, 0, 244));
        field_g7.setEnabled(false);

        field_m7.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        field_m7.setForeground(new java.awt.Color(0, 0, 244));
        field_m7.setEnabled(false);

        jTextField5.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(0, 0, 244));
        jTextField5.setText("MÉDIA FINAL");

        field_h7.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        field_h7.setForeground(new java.awt.Color(0, 0, 244));
        field_h7.setEnabled(false);

        field_p7.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        field_p7.setForeground(new java.awt.Color(0, 0, 244));
        field_p7.setEnabled(false);

        field_a7.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        field_a7.setForeground(new java.awt.Color(0, 0, 244));
        field_a7.setEnabled(false);

        field_c7.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        field_c7.setForeground(new java.awt.Color(0, 0, 244));
        field_c7.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(field_a7)
                            .addComponent(field_g7)
                            .addComponent(field_h7)
                            .addComponent(field_m7)
                            .addComponent(field_p7)
                            .addComponent(field_c7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(field_p7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(field_m7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(field_h7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(field_g7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(field_a7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(field_c7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 244));
        jLabel10.setText("8ª Série");

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        field_g8.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        field_g8.setForeground(new java.awt.Color(0, 0, 244));
        field_g8.setEnabled(false);

        field_m8.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        field_m8.setForeground(new java.awt.Color(0, 0, 244));
        field_m8.setEnabled(false);

        jTextField6.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(0, 0, 244));
        jTextField6.setText("MÉDIA FINAL");

        field_h8.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        field_h8.setForeground(new java.awt.Color(0, 0, 244));
        field_h8.setEnabled(false);

        field_p8.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        field_p8.setForeground(new java.awt.Color(0, 0, 244));
        field_p8.setEnabled(false);

        field_a8.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        field_a8.setForeground(new java.awt.Color(0, 0, 244));
        field_a8.setEnabled(false);

        field_c8.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        field_c8.setForeground(new java.awt.Color(0, 0, 244));
        field_c8.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(field_a8)
                            .addComponent(field_g8)
                            .addComponent(field_h8)
                            .addComponent(field_m8)
                            .addComponent(field_p8)
                            .addComponent(field_c8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(field_p8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(field_m8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(field_h8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(field_g8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(field_a8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(field_c8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Português:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Matemática:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("História:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Geografia:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Arte:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ciências:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 244));
        jLabel11.setText("Aluno:");

        ComboAluno.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        ComboAluno.setForeground(new java.awt.Color(0, 0, 255));
        ComboAluno.setEnabled(false);
        ComboAluno.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                ComboAlunoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        ComboAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboAlunoActionPerformed(evt);
            }
        });

        TabelaNotas.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        TabelaNotas.setForeground(new java.awt.Color(0, 0, 255));
        TabelaNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TabelaNotas);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 255));
        jLabel12.setText("Buscar Aluno:");

        ButtonBuscar.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        ButtonBuscar.setForeground(new java.awt.Color(0, 0, 244));
        ButtonBuscar.setText("Buscar");
        ButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarActionPerformed(evt);
            }
        });

        fieldID.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 244));
        jLabel13.setText("ID:");

        fieldNome.setText("Nome do aluno para descrição");
        fieldNome.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 244));
        jLabel14.setText("Descrição:");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 244));
        jLabel15.setText("Notas pertecem a:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ButonVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ButonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ButtonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ButtonNovoAlunoNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel11)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel15)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(97, 97, 97)
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(fieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(107, 107, 107)
                                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(jLabel7)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(jLabel8)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(jLabel9)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(jLabel10))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ComboAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldBuscarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonBuscar)))
                        .addGap(0, 25, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(fieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonNovoAlunoNota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButonSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButonVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ComboAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(fieldBuscarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboAlunoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_ComboAlunoPopupMenuWillBecomeInvisible
        Aluno aluno_selecionado = new Aluno();
        aluno_selecionado = (Aluno) this.ComboAluno.getSelectedItem();

        JOptionPane.showMessageDialog(null,"Aluno selecionado: " + aluno_selecionado.getId());
    }//GEN-LAST:event_ComboAlunoPopupMenuWillBecomeInvisible

    private void ComboAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboAlunoActionPerformed

    private void ButonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_ButonVoltarActionPerformed

    private void ButtonNovoAlunoNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNovoAlunoNotaActionPerformed
        
        flag=1;
        fieldNome.setEnabled(true);
        ComboAluno.setEnabled(true);
        habilitar();
        ButonSalvar.setEnabled(true);
        ButtonNovoAlunoNota.setEnabled(false);
        ButtonBuscar.setEnabled(false);
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_ButtonNovoAlunoNotaActionPerformed

    private void ButonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonSalvarActionPerformed
        
         if(flag==1){
        Aluno aluno_selecionado = new Aluno();
        aluno_selecionado = (Aluno) this.ComboAluno.getSelectedItem();
         
        
        Notas notas = new Notas(fieldNome.getText(),aluno_selecionado,field_p5.getText(),field_p6.getText(),field_p7.getText(),field_p8.getText(),
                field_m5.getText(), field_m6.getText(), field_m7.getText(), field_m8.getText(),
                field_h5.getText(),field_h6.getText(), field_h7.getText(), field_h8.getText(),
                field_g5.getText(),field_g6.getText(), field_g6.getText(),field_g6.getText(), 
                field_a5.getText(),field_a6.getText(),field_a7.getText(), field_a8.getText(),  
                field_c5.getText(),field_c6.getText(), field_c7.getText(),  field_c8.getText());
        
        
        
        if(Fachada.getInstance().salvar_notas(notas)){
            JOptionPane.showMessageDialog(null, "Notas salvas com sucesso");
            ButtonNovoAlunoNota.setEnabled(true);
            ButonSalvar.setEnabled(false);
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Erro ao salvar notas");
            ButtonNovoAlunoNota.setEnabled(true);
            ButonSalvar.setEnabled(false);
        }
        }
        else{
            Aluno aluno_selecionado = new Aluno();
            aluno_selecionado = (Aluno) this.ComboAluno.getSelectedItem();
            
            notas.setNome(fieldNome.getText());
            notas.setId(Integer.parseInt(fieldID.getText()));
            notas.setAluno((Aluno) this.ComboAluno.getSelectedItem());
           
            
             notas.setPortugues_5(field_p5.getText());
             notas.setPortugues_6(field_p6.getText());
             notas.setPortugues_7(field_p7.getText()); 
             notas.setPortugues_8(field_p8.getText());
             
             
             notas.setMatematica_5(field_m5.getText());
             notas.setMatematica_6(field_m6.getText()); 
             notas.setMatematica_7(field_m7.getText()); 
             notas.setMatematica_8(field_m8.getText());
             
             
             notas.setHistoria_5(field_h5.getText());
             notas.setHistoria_6(field_h6.getText());
             notas.setHistoria_7(field_h7.getText());
             notas.setHistoria_8(field_h8.getText());
             
             
             notas.setGeografia_5(field_g5.getText());
             notas.setGeografia_6(field_g6.getText());
             notas.setGeografia_7(field_g7.getText());
             notas.setGeografia_8(field_g8.getText());
             
             notas.setArte_5(field_a5.getText());
             notas.setArte_6(field_a6.getText());
             notas.setArte_7(field_a7.getText());
             notas.setArte_8(field_a8.getText());
             
            notas.setCiencia_5(field_c5.getText());
            notas.setCiencia_6(field_c6.getText());
            notas.setCiencia_7(field_c7.getText());
            notas.setCiencia_8(field_c8.getText());
                 
             
            Fachada.getInstance().editar_notas(notas);
            ButtonNovoAlunoNota.setEnabled(true);
            ButonSalvar.setEnabled(false);
        }
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_ButonSalvarActionPerformed

    private void ButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarActionPerformed
        ButonSalvar.setEnabled(true);   
        
        
        flag=2;
        fieldID.setEnabled(false);    
        ComboAluno.setEnabled(true);
        habilitar();
        ButtonBuscar.setEnabled(false);  
        ComboAluno.setEnabled(true);   
       
        ButtonNovoAlunoNota.setVisible(false);
        
        
    }//GEN-LAST:event_ButtonEditarActionPerformed

    private void ButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarActionPerformed
        
        
        notas.setPesquisa(fieldBuscarAluno.getText());
        Fachada.getInstance().buscar_notas(notas);
        
        fieldID.setText(String.valueOf(notas.getId()));
        fieldNome.setText(notas.getNome());
        field_p5.setText(notas.getPortugues_5());
        field_p6.setText(notas.getPortugues_6());
        field_p7.setText(notas.getPortugues_7());
        field_p8.setText(notas.getPortugues_8());
        
        field_m5.setText(notas.getMatematica_5());
        field_m6.setText(notas.getMatematica_6());
        field_m7.setText(notas.getMatematica_7());
        field_m8.setText(notas.getMatematica_8());
        
        field_a5.setText(notas.getArte_5());
        field_a6.setText(notas.getArte_6());
        field_a7.setText(notas.getArte_7());
        field_a8.setText(notas.getArte_8());
        
        field_h5.setText(notas.getHistoria_5());
        field_h6.setText(notas.getHistoria_6());
        field_h7.setText(notas.getHistoria_7());
        field_h8.setText(notas.getHistoria_8());
        
        field_g5.setText(notas.getGeografia_5());
        field_g6.setText(notas.getGeografia_6());
        field_g7.setText(notas.getGeografia_7());
        field_g8.setText(notas.getGeografia_8());
        
        field_c5.setText(notas.getCiencia_5());
        field_c6.setText(notas.getCiencia_6());
        field_c7.setText(notas.getCiencia_7());
        field_c8.setText(notas.getCiencia_8());
        
        
        
       
        
        
        
        
        fieldID.setText(String.valueOf(notas.getId()));
                        
        ButtonEditar.setEnabled(true);
       
                
        
        
        
    }//GEN-LAST:event_ButtonBuscarActionPerformed

    private void field_p5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_p5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_p5ActionPerformed

    
    public void habilitar(){
        ComboAluno.setEnabled(true);
        field_a5.setEnabled(true);
        field_a6.setEnabled(true);
        field_a7.setEnabled(true);
        field_a8.setEnabled(true);
        field_p5.setEnabled(true);
        field_p6.setEnabled(true);
        field_p7.setEnabled(true);
        field_p8.setEnabled(true);
        field_m5.setEnabled(true);
        field_m6.setEnabled(true);
        field_m7.setEnabled(true);
        field_m8.setEnabled(true);
        field_h5.setEnabled(true);
        field_h6.setEnabled(true);
        field_h7.setEnabled(true);            
        field_h8.setEnabled(true);  
        field_g5.setEnabled(true);
        field_g6.setEnabled(true);
        field_g7.setEnabled(true);
        field_g8.setEnabled(true);
        field_c5.setEnabled(true);
        field_c6.setEnabled(true);
        field_c7.setEnabled(true);
        field_c8.setEnabled(true);
    }
    
    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{
        "ID","NOME","ID Aluno", "P5", "P6", "P7", "P8"
                , "M5", "M6", "M7", "M8"
                , "H5", "H6", "H7", "H8"
                , "G5", "G6", "G7", "G8"
                , "A5", "A6", "A7", "A8"
                , "C5", "C6", "C7", "C8"
                
        };
        conex_sql.Connection();
        
        conex_sql.executaSql(Sql);
        
        try {
            conex_sql.rs.first();
            do {                
                dados.add(new Object[]{conex_sql.rs.getInt("id"),conex_sql.rs.getString("nome"),conex_sql.rs.getString("id_aluno"),
                    conex_sql.rs.getString("p_05"),conex_sql.rs.getString("p_06"),conex_sql.rs.getString("p_07"),conex_sql.rs.getString("p_08"),
                    conex_sql.rs.getString("m_05"),conex_sql.rs.getString("m_06"),conex_sql.rs.getString("m_07"),conex_sql.rs.getString("m_08"),
                conex_sql.rs.getString("h_05"),conex_sql.rs.getString("h_06"),conex_sql.rs.getString("h_07"),conex_sql.rs.getString("h_08"),
                conex_sql.rs.getString("g_05"),conex_sql.rs.getString("g_06"),conex_sql.rs.getString("g_07"),conex_sql.rs.getString("g_08"),
                conex_sql.rs.getString("a_05"),conex_sql.rs.getString("a_06"),conex_sql.rs.getString("a_07"),conex_sql.rs.getString("a_08"),
                conex_sql.rs.getString("c_05"),conex_sql.rs.getString("c_06"),conex_sql.rs.getString("c_07"),conex_sql.rs.getString("c_08")});
                
            } while (conex_sql.rs.next());
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Erro ao preencher Array List");
        }
        DaoTabela daoTabela = new DaoTabela(dados, colunas);
        TabelaNotas.setModel(daoTabela);
        
        TabelaNotas.getColumnModel().getColumn(0).setPreferredWidth(35);
        TabelaNotas.getColumnModel().getColumn(0).setResizable(false);
        TabelaNotas.getColumnModel().getColumn(1).setPreferredWidth(50);
        TabelaNotas.getColumnModel().getColumn(1).setResizable(false);
        TabelaNotas.getColumnModel().getColumn(2).setPreferredWidth(35);
        TabelaNotas.getColumnModel().getColumn(2).setResizable(false);
        TabelaNotas.getColumnModel().getColumn(3).setPreferredWidth(35);
        TabelaNotas.getColumnModel().getColumn(3).setResizable(false);
        TabelaNotas.getColumnModel().getColumn(4).setPreferredWidth(35);
        TabelaNotas.getColumnModel().getColumn(4).setResizable(false);
        TabelaNotas.getColumnModel().getColumn(5).setPreferredWidth(35);
        TabelaNotas.getColumnModel().getColumn(5).setResizable(false);
        TabelaNotas.getColumnModel().getColumn(6).setPreferredWidth(35);
        TabelaNotas.getColumnModel().getColumn(6).setResizable(false);
        TabelaNotas.getColumnModel().getColumn(7).setPreferredWidth(35);
        TabelaNotas.getColumnModel().getColumn(7).setResizable(false);
        TabelaNotas.getColumnModel().getColumn(8).setPreferredWidth(35);
        TabelaNotas.getColumnModel().getColumn(8).setResizable(false);
        TabelaNotas.getColumnModel().getColumn(9).setPreferredWidth(35);
        TabelaNotas.getColumnModel().getColumn(9).setResizable(false);
        TabelaNotas.getColumnModel().getColumn(10).setPreferredWidth(35);
        TabelaNotas.getColumnModel().getColumn(10).setResizable(false);  
        TabelaNotas.getColumnModel().getColumn(11).setPreferredWidth(35);
        TabelaNotas.getColumnModel().getColumn(12).setResizable(false);
        TabelaNotas.getColumnModel().getColumn(12).setPreferredWidth(35);
        TabelaNotas.getColumnModel().getColumn(13).setResizable(false);
        TabelaNotas.getColumnModel().getColumn(13).setPreferredWidth(35);
        TabelaNotas.getColumnModel().getColumn(14).setResizable(false);
        TabelaNotas.getColumnModel().getColumn(14).setPreferredWidth(35);
        TabelaNotas.getColumnModel().getColumn(15).setResizable(false);
        TabelaNotas.getColumnModel().getColumn(15).setPreferredWidth(35);
        TabelaNotas.getColumnModel().getColumn(16).setResizable(false);
        TabelaNotas.getColumnModel().getColumn(16).setPreferredWidth(35);
        TabelaNotas.getColumnModel().getColumn(17).setResizable(false);
        TabelaNotas.getColumnModel().getColumn(17).setPreferredWidth(35);
        TabelaNotas.getColumnModel().getColumn(18).setResizable(false); 
        TabelaNotas.getColumnModel().getColumn(18).setPreferredWidth(35);
        TabelaNotas.getColumnModel().getColumn(19).setResizable(false);
        TabelaNotas.getColumnModel().getColumn(19).setPreferredWidth(35);
        TabelaNotas.getColumnModel().getColumn(20).setResizable(false);
        TabelaNotas.getColumnModel().getColumn(20).setPreferredWidth(35);
        TabelaNotas.getColumnModel().getColumn(21).setResizable(false);
        TabelaNotas.getColumnModel().getColumn(21).setPreferredWidth(35);
        TabelaNotas.getColumnModel().getColumn(22).setResizable(false);
        TabelaNotas.getColumnModel().getColumn(22).setPreferredWidth(35);
        TabelaNotas.getColumnModel().getColumn(23).setResizable(false);
        TabelaNotas.getColumnModel().getColumn(23).setPreferredWidth(35);
        TabelaNotas.getColumnModel().getColumn(24).setResizable(false);
        TabelaNotas.getColumnModel().getColumn(24).setPreferredWidth(35);
         TabelaNotas.getColumnModel().getColumn(25).setResizable(false);
        TabelaNotas.getColumnModel().getColumn(25).setPreferredWidth(35);
        
        TabelaNotas.getTableHeader().setReorderingAllowed(false);
        TabelaNotas.setAutoResizeMode(TabelaNotas.AUTO_RESIZE_OFF);
        TabelaNotas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex_sql.desconection();
        
        
    } 
    
    
    
    
    
    
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButonSalvar;
    private javax.swing.JButton ButonVoltar;
    private javax.swing.JButton ButtonBuscar;
    private javax.swing.JButton ButtonEditar;
    private javax.swing.JButton ButtonNovoAlunoNota;
    private javax.swing.JComboBox ComboAluno;
    private javax.swing.JTable TabelaNotas;
    private javax.swing.JTextField fieldBuscarAluno;
    private javax.swing.JTextField fieldID;
    private javax.swing.JTextField fieldNome;
    private javax.swing.JTextField field_a5;
    private javax.swing.JTextField field_a6;
    private javax.swing.JTextField field_a7;
    private javax.swing.JTextField field_a8;
    private javax.swing.JTextField field_c5;
    private javax.swing.JTextField field_c6;
    private javax.swing.JTextField field_c7;
    private javax.swing.JTextField field_c8;
    private javax.swing.JTextField field_g5;
    private javax.swing.JTextField field_g6;
    private javax.swing.JTextField field_g7;
    private javax.swing.JTextField field_g8;
    private javax.swing.JTextField field_h5;
    private javax.swing.JTextField field_h6;
    private javax.swing.JTextField field_h7;
    private javax.swing.JTextField field_h8;
    private javax.swing.JTextField field_m5;
    private javax.swing.JTextField field_m6;
    private javax.swing.JTextField field_m7;
    private javax.swing.JTextField field_m8;
    private javax.swing.JTextField field_p5;
    private javax.swing.JTextField field_p6;
    private javax.swing.JTextField field_p7;
    private javax.swing.JTextField field_p8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
