/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_faculdade_Telas;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import projeto_faculdade.DAO.DaoTabela;
import projeto_faculdade.Fachada.Fachada;
import projeto_faculdade.Model.Aluno;
import projeto_faculdade.Model.Responsavel;
import projeto_faculdade.SqlUtil.SQL_Connection;

/**
 *
 * @author Sávio
 */
public class TelaResponsavel extends javax.swing.JFrame {
 SQL_Connection conex_sql =  new SQL_Connection();
    Responsavel responsavel = new Responsavel();
    int flag=0;
    
    public TelaResponsavel() {
        initComponents();
        this.setLocationRelativeTo(null);
       preencherTabela("select *from responsavel order by nome_res");
        
        
        List alunos;
        
        Aluno aluno = new Aluno();
        alunos =Fachada.getInstance().getAllAluno();
       
       int index =0;
       while(alunos.size() > index ){
           ComboAluno.addItem(alunos.get(index));
           index++;
           
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldnome = new javax.swing.JTextField();
        ButttonEditar = new javax.swing.JButton();
        buttonSalvar = new javax.swing.JButton();
        ButtonNovo = new javax.swing.JButton();
        fieldID = new javax.swing.JTextField();
        ComboAluno = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaResp = new javax.swing.JTable();
        LabelBuscar = new javax.swing.JLabel();
        fieldResponsavelBuscar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fieldcpf = new javax.swing.JTextField();
        buttonAdiconarAlu = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonBuscar.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        ButtonBuscar.setForeground(new java.awt.Color(0, 0, 255));
        ButtonBuscar.setText("Buscar");
        ButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Aluno:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Nome:");

        fieldnome.setEnabled(false);

        ButttonEditar.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        ButttonEditar.setForeground(new java.awt.Color(0, 0, 255));
        ButttonEditar.setText("Editar Responsável");
        ButttonEditar.setEnabled(false);
        ButttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButttonEditarActionPerformed(evt);
            }
        });

        buttonSalvar.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        buttonSalvar.setForeground(new java.awt.Color(0, 0, 255));
        buttonSalvar.setText("Salvar Responsável");
        buttonSalvar.setEnabled(false);
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });

        ButtonNovo.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        ButtonNovo.setForeground(new java.awt.Color(0, 0, 255));
        ButtonNovo.setText("Novo Responsável");
        ButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNovoActionPerformed(evt);
            }
        });

        fieldID.setEnabled(false);

        ComboAluno.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        ComboAluno.setForeground(new java.awt.Color(0, 0, 255));
        ComboAluno.setEnabled(false);
        ComboAluno.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                ComboAlunoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("ID:");

        TabelaResp.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        TabelaResp.setForeground(new java.awt.Color(0, 0, 255));
        TabelaResp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TabelaResp);

        LabelBuscar.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        LabelBuscar.setForeground(new java.awt.Color(0, 0, 255));
        LabelBuscar.setText("Buscar Responsável:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("CPF:");

        fieldcpf.setEnabled(false);

        buttonAdiconarAlu.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        buttonAdiconarAlu.setForeground(new java.awt.Color(0, 0, 244));
        buttonAdiconarAlu.setText("Adicionar +1 Aluno");
        buttonAdiconarAlu.setEnabled(false);
        buttonAdiconarAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdiconarAluActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 244));
        jButton1.setText("Voltar ao Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ButtonNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButttonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonAdiconarAlu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fieldnome, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(fieldcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(LabelBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldResponsavelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonBuscar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(fieldnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelBuscar)
                            .addComponent(fieldResponsavelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonBuscar))
                        .addGap(63, 63, 63)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(469, 469, 469))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(ButtonNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButttonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))
                        .addComponent(buttonSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAdiconarAlu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(742, 742, 742))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarActionPerformed

        responsavel.setPesquisa(fieldResponsavelBuscar.getText());
        Fachada.getInstance().buscar_responsavel(responsavel);

        fieldID.setText(String.valueOf(responsavel.getId()));
        fieldnome.setText(responsavel.getNome());
        fieldcpf.setText(responsavel.getCpf());

        ButttonEditar.setEnabled(true);

    }//GEN-LAST:event_ButtonBuscarActionPerformed

    private void ButttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButttonEditarActionPerformed
        
        buttonSalvar.setEnabled(true);

        flag=2;
        fieldID.setEnabled(true);
        fieldnome.setEnabled(true);
        ComboAluno.setEnabled(true);
        fieldID.setEnabled(false);
        fieldcpf.setEnabled(true);

        fieldResponsavelBuscar.setVisible(false);
        LabelBuscar.setVisible(false);
        ButtonBuscar.setVisible(false);

        ButtonNovo.setVisible(false);
        buttonSalvar.setEnabled(true);

    }//GEN-LAST:event_ButttonEditarActionPerformed

    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed

        if(flag==1){
            
            Aluno aluno_selecionado = new Aluno();
            aluno_selecionado = (Aluno) this.ComboAluno.getSelectedItem();

           
            Responsavel responsavel = new Responsavel(fieldnome.getText(),fieldcpf.getText(), aluno_selecionado);
            

            if(Fachada.getInstance().salvar_responsavel(responsavel)){
                JOptionPane.showMessageDialog(null, "Responsável salvo com sucesso");

            }
            else{
                JOptionPane.showMessageDialog(null, "Erro ao salvar Responsável");
            }
            
            buttonAdiconarAlu.setEnabled(true);
        }
        else if(flag==2){
            Aluno aluno_selecionado = new Aluno();
            aluno_selecionado = (Aluno) this.ComboAluno.getSelectedItem();

          

            responsavel.setId(Integer.parseInt(fieldID.getText()));

            responsavel.setNome(fieldnome.getText());
            responsavel.setAluno((Aluno) this.ComboAluno.getSelectedItem());
            responsavel.setCpf(fieldcpf.getText());
            buttonAdiconarAlu.setEnabled(true);
            Fachada.getInstance().editar_responsavel(responsavel);
        }else if(flag==3){
             Aluno aluno_selecionado = new Aluno();
            aluno_selecionado = (Aluno) this.ComboAluno.getSelectedItem();

          

            responsavel.setId(Integer.parseInt(fieldID.getText()));

            responsavel.setNome(fieldnome.getText());
            responsavel.setAluno((Aluno) this.ComboAluno.getSelectedItem());
            responsavel.setCpf(fieldcpf.getText());

            if(Fachada.getInstance().salvar_responsavel(responsavel)){
                JOptionPane.showMessageDialog(null, "Responsável salvo com sucesso");

            }
            else{
                JOptionPane.showMessageDialog(null, "Erro ao salvar Responsável");
            }
        }

    }//GEN-LAST:event_buttonSalvarActionPerformed

    private void ButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNovoActionPerformed
        flag=1;
        fieldcpf.setEnabled(true);
        fieldnome.setEnabled(true);       
        ComboAluno.setEnabled(true);
        buttonSalvar.setEnabled(true);
        buttonSalvar.setEnabled(true);

    }//GEN-LAST:event_ButtonNovoActionPerformed

    private void ComboAlunoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_ComboAlunoPopupMenuWillBecomeInvisible
        Aluno aluno_selecionado = new Aluno();
        aluno_selecionado = (Aluno) this.ComboAluno.getSelectedItem();

        JOptionPane.showMessageDialog(null,"Aluno selecionado: " + aluno_selecionado.getId());
    }//GEN-LAST:event_ComboAlunoPopupMenuWillBecomeInvisible

    private void buttonAdiconarAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdiconarAluActionPerformed
     flag=3;
    }//GEN-LAST:event_buttonAdiconarAluActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{
        "ID", "NOME", "CPF","ID Aluno"
        };
        conex_sql.Connection();
        
        conex_sql.executaSql(Sql);
        
        try {
            conex_sql.rs.first();
            do {                
                dados.add(new Object[]{conex_sql.rs.getInt("id"),conex_sql.rs.getString("nome_res"),
                    conex_sql.rs.getString("cpf"),conex_sql.rs.getString("id_aluno")});
                
            } while (conex_sql.rs.next());
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Erro ao preencher Array List");
        }
        DaoTabela daoTabela = new DaoTabela(dados, colunas);
        TabelaResp.setModel(daoTabela);
        
        TabelaResp.getColumnModel().getColumn(0).setPreferredWidth(50);
        TabelaResp.getColumnModel().getColumn(0).setResizable(false);
        TabelaResp.getColumnModel().getColumn(1).setPreferredWidth(160);
        TabelaResp.getColumnModel().getColumn(1).setResizable(false);
        TabelaResp.getColumnModel().getColumn(2).setPreferredWidth(110);
        TabelaResp.getColumnModel().getColumn(2).setResizable(false);
        TabelaResp.getColumnModel().getColumn(3).setPreferredWidth(110);
        TabelaResp.getColumnModel().getColumn(3).setResizable(false);
     
        
        
        
        
        TabelaResp.getTableHeader().setReorderingAllowed(false);
        TabelaResp.setAutoResizeMode(TabelaResp.AUTO_RESIZE_OFF);
        TabelaResp.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex_sql.desconection();
        
        
    } 
    
    
    
    
    
    
    
    
    
    
    
    
    
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaResponsavel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBuscar;
    private javax.swing.JButton ButtonNovo;
    private javax.swing.JButton ButttonEditar;
    private javax.swing.JComboBox ComboAluno;
    private javax.swing.JLabel LabelBuscar;
    private javax.swing.JTable TabelaResp;
    private javax.swing.JButton buttonAdiconarAlu;
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JTextField fieldID;
    private javax.swing.JTextField fieldResponsavelBuscar;
    private javax.swing.JTextField fieldcpf;
    private javax.swing.JTextField fieldnome;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
